### ISSUE TITLE
Create `examples` folder?

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/odifmap#2]
Instead of accumulating various modules and notebooks in the parent directory, do you want to create an examples folder where we can stash various ways this library can be used?

**Comment by whitews** [comment]
Yes, I thought the same once I started adding multiple examples.

**Comment by benneely** [comment]
OK - I will plan to create the folder `examples` and sub-folders `scripts` and `notebooks` on my next PR. Let me know if something else is preferable.

**Comment by whitews** [comment]
We can have an examples folder in this repo as long as the example script doesn't need extra libraries, i.e. we can put the shapes data set example here to show usage. For the shape data set we fabricate, we'll want to show off the pre-processing functionality for light gradient correction and color correction. Create another issue for the discussion of the shapes example data creation.

We can close this issue once an examples folder is created and committed.

**Comment by benneely** [comment]
@whitews - since, we've broken out the example to anothe repo, should we close this?

**Comment by whitews** [comment]
@benneely You can still create an examples folder in this repo with the shapes data. That data will serve as an agnostic example of how to use this library and possibly be useful for test cases.
