### ISSUE TITLE
`run_pipeline.py` error

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/odifmap#3]
This is a bit of a duplicate issue, but want to be sure it is raised here. Currently the run_pipeline.py script will not work. It expects a `regions.json` file in `mm_e16.5_20x_sox9_sftpc_acta2/light_color_corrected`, but there isn't one there currently.

**Comment by whitews** [comment]
Yep, I must have copied the parent version and it looks like that one is modified by me somewhere along the line. I'll see if I can figure out what I changed and why. Maybe the pipeline examples should do the color correction since the manuscript describes this as part of the process. Would probably be useful for any users looking at the example to see the whole process.

**Comment by benneely** [comment]
I agree. Have you already started this? I might take a stab at doing this with a notebook example so that I can become more familiar with the light and color corrected functions.

**Comment by whitews** [comment]
I have some scripts that do or did this, but it does need to be summarized in one place. What I have tried to avoid is having lungmap specific stuff in this library as we and/or others will likely use this on other images. Now I'm wondering if the core functions in pipeline should go somewhere else (maybe in cv2-extras) and this repo should be our complete scripts demonstrating the pipelines. Thoughts?

**Comment by benneely** [comment]
I'm good with that. Let me know when this is done and I'll update my notebooks to use the new api (i.e. cv2-extras). Instead of calling the module pipeline.py, should we consider calling it segmentation (or something like that) to make the api more intuitive once it's moved?

**Comment by whitews** [comment]
Decided this repo will be the catch all for the pipeline functionality. Renamed repo and moved run_pipeline scripts to new repo called "lungmap-pipeline"
