### ISSUE TITLE
Change `seg_config` key from "color" to "hue"

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/odifmap#4]
This is getting a bit nitpicky, but for those first learning this codebase, hsv space may be a new concept and sticking to keys that match the array dimension may be more intuitive.

**Comment by whitews** [comment]
Not sure what you referring to here. What do you mean by array dimension?

**Comment by benneely** [comment]
I'm going to close this issue. I was under the impression that `utils.generate_color_contours` operated only on the `hue` channel. However, after closer inspection, I see that we are converting back to RGB space to process, so no need to do this.
